name: HAOS Mobile WAN
version: "0.3.15"
slug: ha_cellular_gateway
description: Redundant mobile WAN gateway engine for Home Assistant OS
url: https://github.com/teh-hippo/haos-mobile-wan
arch:
  - aarch64
startup: services
boot: manual
stage: experimental
breaking_versions:
  - "0.3.0"
init: false
host_network: true
hassio_api: true
discovery:
  - ha_cellular_gateway
usb: true
privileged:
  - NET_ADMIN
  - NET_RAW
apparmor: true
timeout: 30
backup_exclude:
  - dnsmasq.leases
options:
  mode: disabled
  dry_run: true
  upstream_mode: hotspot_wifi
  downstream_address: 192.168.80.1/24
schema:
  mode: list(disabled|trial|active)
  dry_run: bool
  upstream_mode: list(hotspot_wifi|iphone_usb)
  downstream_mac: 'match(^$|^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$)?'
  downstream_address: str
  upstream_interface: 'match(^[A-Za-z0-9_.-]{1,15}$)?'
  upstream_address: str?
  upstream_gateway: str?
