driver=nl80211
interface=__AP_INTERFACE__
ctrl_interface=/run/hostapd
ssid=haos-wan-lab
hw_mode=g
channel=1
ieee80211n=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=__SYNTHETIC_PSK__

